#!/usr/bin/env bash

notesDirectory="$1"

redoNotes() {
    find "$notesDirectory" -empty -type f -delete
    ctags -R --exclude='.utils' "$notesDirectory"

    exa --group-directories-first -T -L 8 -I "utils|tags|Alchemy" "$notesDirectory" > "$notesDirectory"/index.md
}

redoNotes
